from __future__ import annotations

from typing import Optional

from .base import ILLMClient, LLMClientConfig


class LocalClient(ILLMClient):
    """
    Lightweight fallback client used in development/test environments.
    Produces deterministic stub responses so the stack can run without
    reaching external APIs.
    """

    def __init__(self, config: Optional[LLMClientConfig] = None) -> None:
        self.config = config or LLMClientConfig(model="local-debug")

    async def complete(
        self,
        *,
        system: Optional[str] = None,
        user: Optional[str] = None,
        format: Optional[str] = None,
    ) -> str:
        sys_part = f"[SYS:{system.strip()}] " if system else ""
        user_part = user.strip() if user else "No prompt provided."
        note = " (json requested)" if format == "json" else ""
        return f"{sys_part}{user_part}{note} — response generated by LocalClient."
